version: '3.8'
services:
  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"

  kafka-producer:
    build:
      context: ./KafkaProducer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka-network

  other-consumer:
    build:
      context: ./KafkaConsumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge